spring.application.name=RestFul_web_services
spring.profiles.active=dev

# Internationalization
spring.messages.basename=messages

# Actuator Endpoints
management.endpoints.web.exposure.include=*

# Default Security User
spring.security.user.name=amit
spring.security.user.password=1234
